import { StyleSheet } from "react-native";
export const C = {
  bg: "#F6F4EE",
  paper: "#FFFEFA",
  ink: "#222722",
  muted: "#7A7E75",
  line: "#E3E3D9",
  accent: "#D95D39",
  pale: "#F8E6DB",
  green: "#50765A",
  dark: "#242D27",
};
export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.bg },
  container: { width: "100%", maxWidth: 760, alignSelf: "center", flex: 1 },
  pad: { paddingHorizontal: 24 },
  row: { flexDirection: "row", alignItems: "center" },
  spread: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  top: {
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 22,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logo: { fontSize: 26, fontWeight: "800", letterSpacing: 1, color: C.ink },
  label: { fontSize: 10, fontWeight: "700", letterSpacing: 2, color: C.muted },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.line,
    alignItems: "center",
    justifyContent: "center",
  },
  h1: {
    fontSize: 32,
    fontWeight: "700",
    color: C.ink,
    letterSpacing: -1,
    lineHeight: 42,
  },
  h2: { fontSize: 22, fontWeight: "700", color: C.ink, lineHeight: 32 },
  body: { fontSize: 15, lineHeight: 26, color: C.ink },
  muted: { fontSize: 12, color: C.muted, lineHeight: 20 },
  section: { paddingTop: 26, paddingBottom: 16 },
  sectionTitle: { fontSize: 19, fontWeight: "700", color: C.ink },
  hero: {
    backgroundColor: C.dark,
    borderRadius: 22,
    padding: 24,
    overflow: "hidden",
    minHeight: 232,
  },
  heroTitle: {
    fontSize: 35,
    lineHeight: 47,
    fontWeight: "600",
    color: C.paper,
    letterSpacing: -1,
  },
  tag: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 5,
    backgroundColor: C.pale,
  },
  tagText: { fontSize: 10, fontWeight: "700", color: C.accent },
  pill: {
    paddingHorizontal: 17,
    paddingVertical: 10,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.paper,
  },
  pillActive: { backgroundColor: C.ink, borderColor: C.ink },
  pillText: { fontSize: 13, fontWeight: "600", color: C.muted },
  card: { paddingVertical: 22, borderBottomWidth: 1, borderColor: C.line },
  feedCard: {
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 17,
    padding: 18,
    marginBottom: 13,
  },
  feedTitle: {
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 29,
    color: C.ink,
    letterSpacing: -0.25,
  },
  cardTitle: { fontSize: 20, fontWeight: "600", lineHeight: 30, color: C.ink },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: "#EAECE2",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { fontSize: 16, fontWeight: "800", color: C.green },
  divider: { height: 1, backgroundColor: C.line },
  nav: {
    borderTopWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    paddingTop: 10,
    paddingBottom: 8,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 64,
    gap: 5,
    paddingVertical: 5,
  },
  navText: { fontSize: 10, color: C.muted },
  input: {
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 12,
    padding: 15,
    color: C.ink,
    fontSize: 15,
    backgroundColor: C.paper,
    minHeight: 50,
  },
  button: {
    backgroundColor: C.ink,
    borderRadius: 13,
    padding: 17,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  buttonText: { color: C.paper, fontSize: 15, fontWeight: "600" },
  error: { backgroundColor: "#FBE6DF", borderRadius: 10, padding: 13 },
  note: { backgroundColor: "#EEEFE6", padding: 14, borderRadius: 12 },
  empty: { paddingVertical: 55, alignItems: "center", gap: 14 },
  metric: { fontSize: 22, fontWeight: "700", color: C.ink },
  smallButton: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 20,
  },
});
